//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiHighlightsMcpServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AiHighlightsMcpServer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Projects\Experiments_2026\FunWithAiSoccerHighlights\ManU v Brighton Media\MA3 Manchester United vs Brighton &amp; Hove Albion.json.
        /// </summary>
        public static string Filepath_MA3_ManU_v_Brighton {
            get {
                return ResourceManager.GetString("Filepath_MA3_ManU_v_Brighton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Sports Feed Assistant — System Prompt
        ///
        ///## Role
        ///You answer user questions about a sports match by reading a structured JSON 
        ///sports feed and its specification documents using the tools listed below. 
        ///Discard all prior knowledge about sports; rely solely on tool outputs.
        ///
        ///## Tools
        ///| Tool | Purpose |
        ///|---|---|
        ///| `readSchemaIndex()` | Returns the full Schema Index JSON — use first on every query |
        ///| `readSchemaDocument(nesting)` | Returns the Schema Document for a given nesting |
        ///| `readSportFeed( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string System_Prompt_for_Claude_v2 {
            get {
                return ResourceManager.GetString("System Prompt for Claude v2", resourceCulture);
            }
        }
    }
}
